apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-boot-admin
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-boot-admin
spec:
  source:
    git:
      url: https://github.com/benwilcock/spring-boot-admin.git
      ref:
        branch: main
